- name: Enable ufw
  ufw:
    state: enabled
    # policy: deny

- name: Set logging
  ufw:
    logging: on

- name: limit SSH connection attempts
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow RPC ports + ssh from internet
  ufw:
    rule: allow
    proto: tcp
    interface: eth0
    direction: in
    src: 0.0.0.0/0
    port: 9090,1317,26657,22

- name: update policy to block
  ufw:
    direction: incoming
    policy: deny

# due to some "feature" this is necessary for ufw to load on reboot
- name: instruct loading of ufw after netfilter-persistent
  lineinfile:
    path: "/lib/systemd/system/ufw.service"
    insertafter: '^Before=network.target'
    line: 'After=netfilter-persistent.service'

- name: enable ufw on startup
  systemd:
    name: ufw
    state: started
    daemon_reload: yes
    enabled: yes