- name: Create Systemd file
  template:
    src: "files/{{ service_full }}"
    dest: "/etc/systemd/system/{{ service_full }}"

- name: enable and start the nodes
  systemd:
    name: "{{ service }}"
    state: started
    daemon_reload: yes
    enabled: yes

