## do this first; seems our IP gets rate-limited if DLing with aria2c
- name: Download Quicksync Checksum
  shell: "wget https://dl2.quicksync.io/{{ chain_id }}-{{ quicksync }}.{{ snapshot_filename }}.checksum"
  args:
    executable: /bin/bash
    chdir: "{{ download_dir }}"
    warn: no
  become: yes
  become_user: "{{ terra_username }}"
  when: quicksync == 'pruned' or quicksync == 'default' or quicksync == 'archive'

- name: Download Quicksync File
  shell: "aria2c -x2 https://dl2.quicksync.io/{{ chain_id }}-{{ quicksync }}.{{ snapshot_filename }}"
  args:
    executable: /bin/bash
    chdir: "{{ download_dir }}"
    warn: no
  become: yes
  become_user: "{{ terra_username }}"
  when: quicksync == 'pruned' or quicksync == 'default' or quicksync == 'archive'
  async: 72000
  poll: 10

# in case of rate-limiting:
# - name: WGET Download Quicksync File
#   shell: "wget https://dl2.quicksync.io/{{ chain_id }}-{{ quicksync }}.{{ snapshot_filename }}"
#   args:
#     executable: /bin/bash
#     chdir: "{{ download_dir }}"
#     warn: no
#   become: yes
#   become_user: "{{ terra_username }}"
#   when: quicksync == 'pruned' or quicksync == 'default' or quicksync == 'archive'

- name: Copy checksum tool
  copy:
    src: "checksum.sh"
    dest: "{{ download_dir }}"
    mode: '0775'

- name: Checksum Quicksync File
  shell: "./checksum.sh {{ chain_id }}-{{ quicksync }}.{{ snapshot_filename }}"
  args:
    executable: /bin/bash
    chdir: "{{ download_dir }}"
    warn: no
  become: yes
  become_user: "{{ terra_username }}"
  when: quicksync == 'pruned' or quicksync == 'default' or quicksync == 'archive'

- name: Delete data dir before unpacking
  file:
    path: "{{ service_homedir }}/data"
    state: absent

- name: Extract Quicksync File
  shell: "tar -I lz4 -xf {{ download_dir }}/{{ chain_id }}-{{ quicksync }}.{{ snapshot_filename }}"
  args:
    executable: /bin/bash
    chdir: "{{ service_homedir }}/"
    warn: no
  become: yes
  become_user: "{{ terra_username }}"
  when: quicksync == 'pruned' or quicksync == 'default' or quicksync == 'archive'
  async: 72000
  poll: 10

