---
# find most recent chainlayer quicksync details, and edit snapshot location:
snapshot_filename: 20220222.0510.tar.lz4
terra_username: terra
moniker: moniker
quicksync: default # choose between pruned, default, archive or none(sync from scratch)
download_dir: "/home/{{ terra_username }}"
lcd_status: "true" # enable LCD
prometheus_flag: "true" # built-in prometheus exporter, chain metrics
filename_full: "{{ chain_id }}-{{ quicksync }}.{{ snapshot_filename }}"

#
# Optional values
#
# private_peer: '' # not used if not supplied
# persistent_peer: '' # not used if not supplied
# ansible_port: 22 # default 22
# ansible_user: root # default current username

#
# No need to edit anything below
#
go_url: https://go.dev/dl/go1.17.1.linux-amd64.tar.gz
go_sha: 010a88df924a81ec21b293b5da8f9b11c176d27c0ee3962dc1738d2352d3c02d
network: terra
service_homedir: "/home/{{ terra_username }}/.terra"
service_executable: terrad
service: terrad
service_full: terrad.service
client_executable: terrad
chain_id: bombay-12
genesis: https://raw.githubusercontent.com/terra-money/testnet/master/bombay-12/genesis.json
repository: terra-money/core/
version: v0.5.16
seeds: 925ecc3de9e2ac65a203beb2333ced1a00c135ed@terra-seed-us.chorus.one:28657,87048bf71526fb92d73733ba3ddb79b7a83ca11e@public-seed.terra.dev:26656,b5205baf1d52b6f91afb0da7d7b33dcebc71755f@public-seed2.terra.dev:26656,5fa582d7c9931e5be8c02069d7b7b243c79d25bf@seed.terra.de-light.io:26656,bae08cc880c20aeda68a5a890a71a9b44ac73cb4@terra-seed-eu.chorus.one:28657
addressbook: https://raw.githubusercontent.com/terra-money/testnet/master/bombay-12/addrbook.json