---
- name: Enable ufw
  ufw:
    state: enabled
    # policy: deny

- name: Set logging
  ufw:
    logging: on

- name: limit SSH connection attempts
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow 9090 port from grafana
  ufw:
    rule: allow
    proto: tcp
    interface: eth0
    direction: in
    src: "{{ grafana_IP_local }}"
    port: 9090


- name: Allow SSH from internet
  ufw:
    rule: allow
    proto: tcp
    interface: eth0
    direction: in
    src: 0.0.0.0/0
    port: 22
  when: allow_public_ssh == "yes"

- name: update policy to block
  ufw:
    direction: incoming
    policy: deny

# due to some "feature" this is necessary for ufw to load on reboot
- name: instruction to load ufw after the netfilter-persistent
  lineinfile:
    path: "/lib/systemd/system/ufw.service"
    insertafter: '^Before=network.target'
    line: 'After=netfilter-persistent.service'

- name: enable ufw on startup
  systemd:
    name: ufw
    state: started
    daemon_reload: yes
    enabled: yes