---
# tasks file for deploy grafana

- name: Install nessesary package
  apt: 
    update_cache: true
    state: latest
    pkg:
      - acl
      - apt-transport-https

- name: add grafana gpg key
  shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -
  become: yes
  # become_user: "{{ grafana_username }}"
  become_user: root

- name: add grafana repo 
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana
  become: yes
  become_user: root

- name: Install grafana
  apt: 
    name: grafana
    state: present
    update_cache: yes
  become: yes
  become_user: root

- name: Enable and start grafana service
  service:
    name: grafana-server
    enabled: yes
    state: started