server_binary: 'prometheus'
server_binary_dest: '/usr/bin/prometheus'
server_service: 'prometheus.service'
server_service_dest: '/etc/systemd/system/prometheus.service'

prometheus_user: 'prometheus'
prometheus_server_name: 'prometheus'

client_information_dict:
    'terra_node1': '{{ full_node_IPs_local[0] }}:9100'
    'terra_node2': '{{ full_node_IPs_local[1] }}:9100'
    'terra_node3': '{{ full_node_IPs_local[2] }}:9100'
    'terra_node1_chaindata': '{{ full_node_IPs_local[0] }}:26660'
    'terra_node2_chaindata': '{{ full_node_IPs_local[1] }}:26660'
    'terra_node3_chaindata': '{{ full_node_IPs_local[2] }}:26660'
    'haproxy': '{{ haproxy_IP_local }}:9100'